[options]
admin_passwd = __ADMIN_PASSWD__

addons_path = /opt/odoo/odoo/addons,/opt/odoo/extra-addons/account-analytic,/opt/odoo/extra-addons/account-financial-reporting,/opt/odoo/extra-addons/account-financial-tools,/opt/odoo/extra-addons/account-invoicing,/opt/odoo/extra-addons/account-payment,/opt/odoo/extra-addons/account-reconcile,/opt/odoo/extra-addons/agreement,/opt/odoo/extra-addons/ai,/opt/odoo/extra-addons/bank-payment,/opt/odoo/extra-addons/bank-statement-import,/opt/odoo/extra-addons/commission,/opt/odoo/extra-addons/contract,/opt/odoo/extra-addons/crm,/opt/odoo/extra-addons/dms,/opt/odoo/extra-addons/field-service,/opt/odoo/extra-addons/fleet,/opt/odoo/extra-addons/geospatial,/opt/odoo/extra-addons/helpdesk,/opt/odoo/extra-addons/hr,/opt/odoo/extra-addons/hr-expense,/opt/odoo/extra-addons/iot,/opt/odoo/extra-addons/knowledge,/opt/odoo/extra-addons/l10n-brazil,/opt/odoo/extra-addons/mail,/opt/odoo/extra-addons/maintenance,/opt/odoo/extra-addons/management-system,/opt/odoo/extra-addons/manufacture,/opt/odoo/extra-addons/manufacture-reporting,/opt/odoo/extra-addons/mis-builder,/opt/odoo/extra-addons/partner-contact,/opt/odoo/extra-addons/product-attribute,/opt/odoo/extra-addons/project,/opt/odoo/extra-addons/purchase-workflow,/opt/odoo/extra-addons/queue,/opt/odoo/extra-addons/repair,/opt/odoo/extra-addons/reporting-engine,/opt/odoo/extra-addons/sale-reporting,/opt/odoo/extra-addons/sale-workflow,/opt/odoo/extra-addons/server-env,/opt/odoo/extra-addons/server-tools,/opt/odoo/extra-addons/server-ux,/opt/odoo/extra-addons/sign,/opt/odoo/extra-addons/stock-logistics-request,/opt/odoo/extra-addons/stock-logistics-warehouse,/opt/odoo/extra-addons/stock-logistics-workflow,/opt/odoo/extra-addons/storage,/opt/odoo/extra-addons/timesheet,/opt/odoo/extra-addons/web,/opt/odoo/extra-addons/website

data_dir = /opt/odoo/.local/share/Odoo

db_host = __DB_HOST__
db_port = __DB_PORT__
db_user = __DB_USER__
db_password = __DB_PASSWORD__
db_name = __DB_NAME__
db_maxconn = 64

list_db = False
dbfilter = ^odoo$

proxy_mode = True

http_interface = 127.0.0.1
http_port = 8069
gevent_port = 8072

workers = 2
max_cron_threads = 1

limit_memory_soft = 2147483648
limit_memory_hard = 2684354560
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200
limit_time_real_cron = 600

logfile = /var/log/odoo/odoo.log
log_level = info
log_handler = :INFO
logrotate = True

without_demo = True
